# Generated by Django 4.2.5 on 2023-09-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcustomer',
            name='customer_number',
            field=models.CharField(max_length=200),
        ),
    ]
