# Generated by Django 4.2.5 on 2023-09-26 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('additem', '0002_rename_item_item_item_name'),
        ('order', '0002_rename_customerid_order_customerid_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Orderid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('itemid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='additem.item')),
            ],
        ),
    ]
