# Generated by Django 4.2.5 on 2023-09-29 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('additem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('OrderItemID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.PositiveIntegerField()),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='additem.item')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
