# Generated by Django 4.2.5 on 2023-09-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='CustomerID',
            new_name='customerid_id',
        ),
    ]
