# Generated by Django 4.2.5 on 2023-10-17 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0005_item_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='customer',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ItemAttribute',
        ),
        migrations.AddField(
            model_name='thickness',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='additem.item'),
        ),
        migrations.AddField(
            model_name='size',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='additem.item'),
        ),
        migrations.AddField(
            model_name='rate',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='additem.item'),
        ),
    ]
