# Generated by Django 4.2.5 on 2023-10-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0008_itemvariation_remove_size_item_remove_thickness_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariation',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
