# Generated by Django 4.2.5 on 2023-10-18 01:11

import additem.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0011_alter_itemvariation_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariation',
            name='size',
            field=additem.models.FractionField(),
        ),
    ]
