# Generated by Django 4.2.5 on 2023-10-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additem', '0012_alter_itemvariation_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='customer_name',
        ),
        migrations.AlterField(
            model_name='itemvariation',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
